question_data = [{"type": "multiple", "difficulty": "medium", "category": "History",
                   "question": "Where and when was the first cardboard box made for industrial use?",
                   "correct_answer": "England, 1817",
                   "incorrect_answers": ["United States, 1817", "England, 1917",
                                         "United States, 1917"]},
                  {"type": "multiple", "difficulty": "medium", "category": "Geography",
                   "question": "What is the largest Muslim country in the world?",
                   "correct_answer": "Indonesia",
                   "incorrect_answers": ["Pakistan", "Saudi Arabia", "Iran"]},
                  {"type": "multiple", "difficulty": "easy",
                   "category": "Entertainment: Books",
                   "question": "What was Sir Handel's original name in The Railway Series and its animated counterpart Thomas and Friends?",
                   "correct_answer": "Falcon",
                   "incorrect_answers": ["Eagle", "Kyte", "Swallow"]},
                  {"type": "boolean", "difficulty": "easy",
                   "category": "Science: Computers",
                   "question": "The programming language Python is based off a modified version of JavaScript&quot.",
                   "correct_answer": "False", "incorrect_answers": ["True"]},
                  {"type": "multiple", "difficulty": "hard",
                   "category": "Entertainment: Music",
                   "question": "Which of these songs is not by Tatsuro Yamashita?",
                   "correct_answer": "Lucky Lady Feel So Good ",
                   "incorrect_answers": ["Merry-Go Round", "Let's Dance Baby",
                                         "Love Talking"]},
                  {"type": "multiple", "difficulty": "hard",
                   "category": "Entertainment: Video Games",
                   "question": "In the game The Sims, how many Simoleons does each family start with?",
                   "correct_answer": "20,000",
                   "incorrect_answers": ["10,000", "15,000", "25,000"]},
                  {"type": "multiple", "difficulty": "medium",
                   "category": "Entertainment: Video Games",
                   "question": "What is the name of the common, gun-toting enemies of the Oddworld video game series?",
                   "correct_answer": "Sligs",
                   "incorrect_answers": ["Scrabs", "Slogs", "Glukkons"]},
                  {"type": "multiple", "difficulty": "easy",
                   "category": "General Knowledge",
                   "question": "What is the profession of Elon Musk's mom, Maye Musk?",
                   "correct_answer": "Model",
                   "incorrect_answers": ["Professor", "Biologist", "Musician"]},
                  {"type": "multiple", "difficulty": "easy",
                   "category": "Entertainment: Music",
                   "question": "The Rush song YYZ derives its name from the IATA aiport identification code for which city?",
                   "correct_answer": "Toronto",
                   "incorrect_answers": ["Vancouver", "Ottawa", "Calgary"]},
                  {"type": "multiple", "difficulty": "medium",
                   "category": "Entertainment: Television",
                   "question": "The 1985 Toyota Corolla AE86 was the hero car for what anime? ",
                   "correct_answer": "Initial D",
                   "incorrect_answers": ["Wangan Midnight", "Ghost MF", "Ex Driver"]}]
